coopengo/trytond

trytond/ir/model.py
trytond/ir/view/model_print_model_graph_start_form.xml

Function fields may render the ir.model.graph report unusable if there are a
lot of them, and if the objective is a database visualisation tool.
Fix #4940

trytond : Optionaly ignore function fields in ir.model.graph

---

trytond/pool.py

Post init hooks should be triggered at the end of Pool.setup in order to be
sure they are properly called when upgrading the database.

trytond : Trigger post_init after setup

---

trytond/modules/__init__.py
trytond/pool.py

Some hooks will not be necessary on updates, others will only be required when
updating some modules, etc... So we add an 'update' argument to hooks so that
it becomes possible to activate the hook or not depending on the context.
Consequently, we move the logging part from the post_init method to inside the
hook, so the log is not filled with hooks which aren't actually triggered.

trytond : Add update parameter to post init hooks

---

trytond/report/report.py

report: avoid coog server tail crash when logging unoconv binaries

---

trytond/rpc.py

It is required that the _datetime_exclude key be True to read records
"right before" something happens, but the server actually drops the key
since it is considered private.
Fix #6582

Add _datetime_exclude to private context keys exception

---

trytond/model/modelstorage.py

The `_save_values` method checks and sets the reverse field of O2M fields if necessary, but it does not check whether the field is a function field. So this may causes errors, because `field.field` is `None`.

trytond : Do not to try to set reverse O2M field for function fields

---

trytond/modules/__init__.py

In tests, the server is called right after being updated. In
this case, the post_init method must be called anyway for hooks
that are only called when not updating

trytond : Always call post_init(None)

---

trytond/model/modelview.py

The rec_name may not be available for newly created instances, and
we should not get it anyway even if it was because the main data
will not be returned

trytond : Only load rec_names for saved instances

---

trytond/model/modelview.py

This is especially useful when creating / modifying views to avoid
a server reload after each modification.
Just add "disable_fields_view_get_cache = True" under the cache
section of trytond.conf

trytond : Add option to ignore view caching

---

trytond/tests/test_tryton.py

A simply "elegant" solution to the concurrent access errors causing tests to fail

tests: fix concurrent access when dropping database

---

trytond/cache.py
trytond/cache_redis.py
trytond/ir/ui/view.py

Ce qui intéressant à voir: git diff 4.6 -- cache.py (before and after)
Intérêt: tout le cache est dans redis => no overhead for clean / resets
Non serializable objects are cached via memoize
Fix #8160

one active cache implem - non serializable to memoize

---

trytond/ir/model.py
trytond/model/modelstorage.py

This allows fast return when the checked model has no record in
ir.model.data which is the most common case. This allow to prevent to
search for non existing records.

Add cache for check_xml_record

---

trytond/ir/module.py
trytond/iwc.py
trytond/pool.py

Fix #8760
- Listener creation moved from Pool.start to Pool.init (start is called before forking)
- Broadcast mooved from ir.module workflow to Pool.init (trytond-admin does not trigger workflow)
- worker pid is not safe to identify worker (multi-container, multi-host) => id = hostname-pid

iwc: fix inter worker communication (not trigger due to tryton changes)

---

trytond/wsgi.py

trytond: Use FORBIDDEN code instead of unauthorized to avoid client crash

---

trytond/tests/test_tryton.py

This is so that we can automatically add 'api' module the the extras of all module test case, while keeping a correct name for the db cache.

test_tryton: use module as default cache_name for db_cache

---

trytond/config.py
trytond/report/report.py

This is a workaround to
Fix #10833
while waiting for potential real fix on #14733

report: add 2 retries by default on calls to unoconv api

---

trytond/application.py
trytond/protocols/jsonrpc.py

The pypy module of wsgi does not allow to specify the name
of the variable to use as the application, so we must
expose an 'application' attribute
Fix #00000

trytond: Make wsgi application pypy compatible

---

trytond/backend/postgresql/database.py

Without this, the connections are not closed until
they are GC'ed, which can take some time.
Also, if there are tens of databases to scan, we
may exhaust the connection pool of the database
(actually @jmousset found this one almost at the same time)

database: Manually close test connections

---

doc/ref/pyson.rst
trytond/pyson.py

PYSON's DateTime defaults to the current time in UTC

---

trytond/model/modelstorage.py

`ModelStorage.create_date` currently returns `lazy_gettext('ir.msg_created_by')` as its message value, changed so it correctly uses `ir.msg_created_at`.

Fixed 'create_date' message in ModelStorage 

---

trytond/backend/postgresql/database.py
trytond/tests/test_field_text.py

Use the same heuristic to compute backend full text search configuration for both operands

---

trytond/tests/tools.py

Fix #0
Pour éviter de futures confusions

Force named kwargs in activate_modules

---

trytond/backend/postgresql/database.py
trytond/cache.py

Le fix pour psycopgcffi ne fonctionne pas quand le DSN a déjà une query string.
Ce changement fix cela.

Fallback name fix
