coopengo/trytond

- trytond/tests/run-tests.py
> test: use uuid insteadof time to name test db (conflicts)

- trytond/application.py
> log: use default logging format when using wsgi

- trytond/res/user.py
- trytond/transaction.py
> trytond: Handle add sub_transactions to a transaction

- trytond/protocols/jsonrpc.py
> wsgi: add rpc to uwsgi log vars

- trytond/cache.py
- trytond/model/modelsql.py
- trytond/perf_analyzer.py
- trytond/protocols/dispatcher.py
- trytond/security.py
- trytond/security_redis.py
> avoid unuseful new_transaction - session on cache

- trytond/perf_analyzer.py
- trytond/protocols/dispatcher.py
- trytond/protocols/jsonrpc.py
- trytond/security.py
> Cleaning and refactoring before session management

- trytond/cache_serializer.py
- trytond/protocols/dispatcher.py
- trytond/res/user.py
- trytond/security.py
- trytond/security_redis.py
> redis: manage session on redis

- trytond/res/user.py
- trytond/security.py
- trytond/security_redis.py
> session: [1.12] improve redis session management

- trytond/config.py
- trytond/report/report.py
> py3: Some fixes (config override) + get unoconv out of coog image

- trytond/cache.py
- trytond/model/modelsql.py
- trytond/perf_analyzer.py
- trytond/protocols/dispatcher.py
- trytond/res/user.py
- trytond/security.py
- trytond/security_redis.py
> 7610 avoid unuseful transaction report

- trytond/security.py
- trytond/security_redis.py
> session: basic implem for session audit module

- trytond/protocols/dispatcher.py
- trytond/protocols/wrappers.py
- trytond/security.py
> support token authorization

- trytond/ir/action.py
- trytond/model/modelview.py
PR relative à https://support.coopengo.com/issues/7934
> Add form_toolbar keyword

- trytond/model/modelsql.py
The call to Translation.delete_ids has a cost as it does search queries.
So it is better to not call it if we already know that there is nothing
to delete.
> Delete translations only when model has translatable field

- trytond/ir/view/icon_view_form.xml
cherry-picked from : http://hg.tryton.org/trytond/rev/407e4f7c8c0d
Fix #8482
> trytond: Allow field name on image tag

- trytond/protocols/dispatcher.py
- trytond/res/user.py
> add user and party informations to pref RPC

- trytond/model/fields/field.py
- trytond/model/modelview.py
> trytond: add depends of field to depends of on_change method

- trytond/tests/test_tryton.py
- trytond/tests/tools.py
> test: fix db lock errors on test

- CHANGELOG
- trytond/ir/ui/form.rnc
- trytond/ir/ui/form.rng
- trytond/ir/ui/tree.rnc
- trytond/ir/ui/tree.rng
> trytond: backport http://hg.tryton.org/trytond/rev/052a3d2f1cd4

- trytond/ir/module.py
- trytond/model/modelview.py
- trytond/modules/__init__.py
- trytond/tests/test_tryton.py
cherry-picked from https://codereview.tryton.org/45211002/#ps1
Fix #8910
> trytond: Simplify the creation of dependencies graph

- doc/ref/models/fields.rst
- trytond/model/modelview.py
- trytond/tests/test_field_depends.py
cherry-picked from https://hg.tryton.org/trytond/rev/a57cd35eec06
Fix #8725
> Make depends on methods generic to any method

- CHANGELOG
- trytond/modules/__init__.py
> Don't auto_uninstall module

- CHANGELOG
- trytond/cache_redis.py
> Add ttl on redis cache, default 12 hours, configurable on config and on code

- trytond/model/dictschema.py
> trytond: Add sequence_order to dict schema

- trytond/model/fields/selection.py
https://support.coopengo.com/issues/10592
> Order selection field with instance method on column

- trytond/protocols/wrappers.py
> Wrapper.py: 2to3 token

- trytond/ir/translation.py
when executing the translation clean wizard
> Fix merge issue: translation where wrongly deleted

- trytond/application.py
> trytond: Ensute kubernetes logging whether the env variable is not set

- trytond/application.py
> trytond: Hot fix typo from commit a2311cd2

- trytond/protocols/wrappers.py
Needed for : https://github.com/coopengo/trytond-cryptolog/pull/7/
see https://support.coopengo.com/issues/12686
> wrappers: add with_pool_by_config wrapper

- trytond/protocols/dispatcher.py
This makes reading the DEBUG log level a little easier,
and can be activated through the format_result_logs and
format_parameters_logs flags in the configuration file
of trytond
> trytond: Allow to format json in debug logs

- trytond/cache.py
This is necessary for cases where there are a lot of
caches to clear at the same time, because the total
size of the NOTIFY payload is limited
> cache: Reset channel cache by chunks

- doc/ref/models/models.rst
- trytond/model/dictschema.py
> Add help text to Dict keys

- bin/trytond-admin
- bin/trytond-console
- trytond/backend/__init__.py
- trytond/model/modelstorage.py
- trytond/tests/__init__.py
- trytond/tests/export_data.py
- trytond/tests/field_context.py
- trytond/tests/history.py
- trytond/tests/modelview.py
- trytond/tests/mptt.py
- trytond/tests/run-tests.py
- trytond/tests/trigger.py
- trytond/tests/wizard.py
- trytond/tests/workflow.py
- trytond/transaction.py
> Cache some performance sensible config values at the module level

- CHANGELOG
- trytond/model/dictschema.py
- trytond/model/fields/dict.py
- trytond/tests/test_field_dict.py
> trytond: Add MultiSelection Entry to dict

- trytond/pyson.py
> Add start value to PYSON Date and DateTime

- trytond/ir/note.py
> note: restore tryton original of note.write

- bin/trytond-admin
- trytond/admin.py
- trytond/backend/postgresql/init_upgrade_version_control.sql
- trytond/cache.py
- trytond/commandline.py
> trytond: Upgrade only when necessary with new command line

- trytond/ir/note.py
- trytond/tests/__init__.py
- trytond/tests/note.py
- trytond/tests/test_note.py
> Do not write metadata on ir.note when writing only on the unread field

- trytond/admin.py
> admin: fix translation update when using check_update option

- trytond/admin.py
- trytond/model/modelsql.py
> Do not remove indexes automatically

- trytond/admin.py
- trytond/ir/module.py
- trytond/pool.py
> Disable auto cache when updating modules

- trytond/model/modelstorage.py
> Set _init_values when reading

- trytond/model/fields/field.py
> Ensure dependencies of fields are also loaded on Form display

- trytond/application.py
> uwsgi: Properly reset cache / iwc threads after fork

- trytond/application.py
- trytond/pool.py
Abandonned in favor of https://github.com/coopengo/coog/pull/4757
> Remove bad attempt at fixing #17308

- trytond/model/union.py
> model: cast id to bigint in union mixin

- CHANGELOG
- doc/ref/models/fields.rst
- trytond/backend/table.py
> Allow to retrieve column's SQL type from backend

- trytond/model/modelstorage.py
> Compute once selection field's value when possible

- CHANGELOG
- trytond/model/fields/function.py
- trytond/model/modelstorage.py
> Eager load Function field with same multiple getter

- trytond/report/report.py
> report: Force encoding of csv convert

- trytond/model/modelstorage.py
- trytond/model/modelview.py
> Use vanilla patch instead of custom patch

- trytond/sentry.py
"raven" was deprecated some times ago already, with
"sentry_sdk" as its replacement.
Fix #18921
> trytond: Update Sentry library

- trytond/modules/__init__.py
Warning: this was tested with the MemoryCache and a
postgresql-synced cache clearing (clean_timeout=0)
Rather than clearing nothing, we delay the cache clear
until after all modules were updated.
Fix #18995
> modules: Actually clear caches when updating

- trytond/protocols/dispatcher.py
- trytond/security.py
> security: Only reset session once per call, use autocommit

- trytond/convert.py
> trytond: Always update database when noupdate=0

- CHANGELOG
- trytond/res/__init__.py
- trytond/res/user.py
> Protect trusted devices against brute force attack

- trytond/backend/postgresql/database.py
- trytond/backend/postgresql/table.py
> Use psycopg' sql module for DDL queries

- trytond/backend/postgresql/database.py
- trytond/backend/postgresql/table.py
- Concatenate cascade string to drop table before converting to SQL
- Add missing rename work in postgresql sequence rename
> Different DDL fixes

- trytond/model/modelsql.py
> Compute default values on creation only once per schema of missing default values

- trytond/tests/test_tools.py
- trytond/tools/domain_inversion.py
> Use specific search domain for reference field searches

- trytond/cache.py
> cache: Remove client key from cache's context

- CHANGELOG
- trytond/ir/session.py
> Reset less often the user sessions

- CHANGELOG
- doc/topics/configuration.rst
- trytond/model/dictschema.py
- trytond/model/modelview.py
> Use a single RPC call to get dictionary key definitions

- trytond/model/dictschema.py
> Re-add get_keys to sync with upstream

- trytond/model/modelsql.py
> Add implicitely write_date to read columns only when reading already other columns

- trytond/cache.py
> Remove also _request from context

- trytond/model/modelsql.py
- trytond/tests/test_modelsql.py
> Call Function.get by bunch of cache size

- trytond/bus.py
- trytond/cache.py
- trytond/iwc.py
- trytond/pool.py
- trytond/tests/test_tryton.py
> Use autocommit for LISTEN

- trytond/model/fields/selection.py
- trytond/model/modelsql.py
- trytond/tests/test_field_selection.py
> Get directly the string value of Selection fields in non editable tree views

- trytond/res/routes.py
> Add database connection test to livenessness call

- trytond/model/modelsql.py
> Correctly use ':string'

- trytond/cache.py
review365521003
issue10528
Fix #20395
> cache: Do not reset cache on commit and clear

- CHANGELOG
- doc/ref/models/fields.rst
- trytond/backend/sqlite/database.py
- trytond/ir/sequence.py
- trytond/model/fields/char.py
- trytond/tests/field_char.py
- trytond/tests/test_field_char.py
> Add option to remove leading and trailing whitespaces from fields.Char

- trytond/backend/postgresql/table.py
- trytond/backend/sqlite/table.py
- trytond/backend/table.py
> Only test column varchar size when set

- trytond/convert.py
Fix [#20636](https://support.coopengo.com/issues/20636)
> Correctly update noupdate tag in database

- trytond/protocols/wrappers.py
> wrappers: move call to security.check_token to user_id method

- CHANGELOG
- trytond/model/modelsql.py
- trytond/tests/test_modelsql.py
> Use UNION for 'Or'-ed domain with subqueries

- trytond/cache.py
> Cache context cleaning 21081

- CHANGELOG
- trytond/res/user.py
> user: Fetch cached context and improve it with transaction context information

- CHANGELOG
- trytond/tests/test_tools.py
- trytond/tools/domain_inversion.py
> Deduplicate entries in domain inversion's simplify

- trytond/cache.py
> cache: Add cleaning code that disappeared during the 6.0 upgrade

- CHANGELOG
- trytond/backend/__init__.py
- trytond/backend/database.py
- trytond/backend/postgresql/__init__.py
- trytond/backend/postgresql/database.py
- trytond/backend/sqlite/__init__.py
- trytond/backend/sqlite/database.py
- trytond/exceptions.py
- trytond/ir/model.py
- trytond/model/modelstorage.py
- trytond/protocols/dispatcher.py
- trytond/rpc.py
- trytond/tests/test_transaction.py
- trytond/transaction.py
> Add database timeout parameter on RPC calls

- trytond/res/user.py
> Remove useless get_login cache

- trytond/model/modelstorage.py
> Limit size of read ids for better cache alignment

- trytond/error_handling.py
> Passthrough werkzeug Unauthorized errors

- trytond/report/report.py
> trytond: Add hook to apply custom report style content at render

- trytond/model/active.py
> trytond: [22.14] Add hook override to allow inactive record modification [CUSTOM]

- CHANGELOG
- trytond/error_handling.py
> Don't catch timeout exceptions in error handler

- trytond/report/report.py
Fix #PROCK-279
Report => Coog 22.14
**Test réalisé :**  Génération d'un rapport de bordereaux de chèques (master)
> Report contexts get a copy of records with the 'objects' key [CUSTOM]

- trytond/report/report.py
> Report contexts get a copy of records with the 'objects' key [CUSTOM] (#225)

- trytond/report/report.py
> Report contexts get a copy of records with the 'objects' key [CUSTOM] (#225) (#228)

- doc/topics/configuration.rst
- trytond/__init__.py
- trytond/backend/postgresql/database.py
> Set the fallback application name when connecting to postgres [PREVIEW]

- setup.py
- tox.ini
- trytond/backend/postgresql/database.py
> Add support for psycopg2cffi and PyPy [CUSTOM]

- trytond/cache.py
> Keep using _database_cache if the specific cache hasn't been reset [PREVIEW]

- CHANGELOG
- trytond/backend/postgresql/table.py
- trytond/backend/sqlite/table.py
- trytond/backend/table.py
- trytond/model/modelsql.py
> Use singleton for TableHandler [PREVIEW]

- trytond/ir/action.py
Fix #PJAZZ-704
Before PR:
After PR:
> trytond: Sorting actions by their decoded names

- doc/ref/tools/index.rst
- doc/ref/tools/logging.rst
- trytond/protocols/dispatcher.py
- trytond/tests/test_tools.py
- trytond/tools/logging.py
https://foss.heptapod.net/tryton/tryton/-/merge_requests/387
> Shorten arguments when logging [PREVIEW]

- trytond/model/active.py
> trytond: Add hook override to allow inactive record modification [CUSTOM]

- CHANGELOG
- trytond/convert.py
Fix #PJAZZ-840
needed for: https://github.com/coopengo/coog/pull/8611
> Allow users to reset no_update records from xml description [CUSTOM]

- trytond/ir/ui/tree.rnc
- trytond/ir/ui/tree.rng
Fix #00000
Related to PJAZZ1100
> Allow width attribute on buttons while in tree view [CUSTOM]
